#ifndef RPG_INVENTORY_REVAMP_CHARACTER_CLASS_H
#define RPG_INVENTORY_REVAMP_CHARACTER_CLASS_H

enum class CharacterClass {
  WARRIOR,
  MAGE,
  RANGER,
  CLERIC
};

#endif //RPG_INVENTORY_REVAMP_CHARACTER_CLASS_H
